# SPDX-FileCopyrightText: 2025-2026 Michael Serajnik <https://github.com/mserajnik>
# SPDX-License-Identifier: AGPL-3.0-or-later

name: Lint

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    name: Lint
    uses: mserajnik/docker-deploy-workflows/.github/workflows/shared-lint.yaml@v1
    with:
      extra-dockerfiles: |
        docker/server/Dockerfile.node
      compose-files: |
        compose.yaml.example
